Totem:
  # The probability that totem doesn't work
  # 100 = 100% (totem always works)
  # 0 = 0% (totem never works)
  # ONLY AFFECTS VANILLA TOTEMS
  chance: 100
  # Show totem animation when using a totem
  # ONLY AFFECTS CUSTOM TOTEMS
  playAnimation: true

