Totem:
  # The probability that totem doesn't work
  # 100 = 100% (totem always works)
  # 0 = 0% (totem never works)
  # ONLY AFFECTS VANILLA TOTEMS
  chance: 100
  # Health that totem gives when it works
  # 2.0 = 2 hearts
  # 0.0 = 0 hearts
  # ONLY AFFECTS CUSTOM TOTEMS
  health: 2.0
  # If true, totem effect will be displayed when it works
  playAnimation: true

